document.addEventListener('DOMContentLoaded',()=>{
  const project=document.querySelector('#tagProject'),scale=document.querySelector('#tagScale'),definition=document.querySelector('#definitionPanel'),matching=document.querySelector('#matchingPanel');
  const scaleOptions={
    '慢病管理项目':['用药依从性量表','PHQ-9 抑郁筛查量表'],
    '肿瘤随访项目':['治疗方案评估量表','NRS 疼痛评分量表'],
    '真实世界研究项目':['患者基本信息采集']
  };
  const refreshScales=()=>{const list=scaleOptions[project.value]||[];scale.innerHTML='<option value="all">全部量表</option>'+list.map(item=>`<option value="${item}">${item}</option>`).join('');scale.disabled=project.value==='all'};
  const filterRows=()=>{
    const selectedProject=project.value,selectedScale=scale.value;
    document.querySelectorAll('#definitions > tbody > .tag-domain-detail').forEach(row=>row.remove());document.querySelectorAll('#definitions > tbody > tr').forEach(row=>row.classList.remove('expanded'));
    [['#definitions','#definitionEmpty'],['#matching','#matchingEmpty']].forEach(([table,empty])=>{let count=0;document.querySelectorAll(`${table} > tbody > tr:not(.tag-domain-detail)`).forEach(row=>{const show=(selectedProject==='all'||row.dataset.project===selectedProject)&&(selectedScale==='all'||row.dataset.scale===selectedScale);row.hidden=!show;if(show)count++});document.querySelector(empty).hidden=count!==0});
  };
  project.addEventListener('change',()=>{refreshScales();filterRows()});scale.addEventListener('change',filterRows);document.querySelector('#queryTags').addEventListener('click',filterRows);document.querySelector('#resetTags').addEventListener('click',()=>{project.value='all';refreshScales();filterRows()});refreshScales();filterRows();
  document.querySelectorAll('.tag-tabs button').forEach(button=>button.addEventListener('click',()=>{const isDefinition=button.dataset.tab==='definition';definition.hidden=!isDefinition;matching.hidden=isDefinition;document.querySelectorAll('.tag-tabs button').forEach(item=>item.classList.toggle('active',item===button))}));
  const domainStats={
    '高依从性患者':[['高依从性','用药依从性量表',126,98],['中等依从性','用药依从性量表',108,71],['低依从性','用药依从性量表',68,49]],
    '心理风险关注':[['无风险','PHQ-9 抑郁筛查量表',156,0],['轻度风险','PHQ-9 抑郁筛查量表',89,16],['中重度风险','PHQ-9 抑郁筛查量表',69,31]],
    '靶向治疗患者':[['靶向治疗中','治疗方案评估量表',218,174],['靶向治疗后随访','治疗方案评估量表',224,0]],
    '高疼痛风险':[['中度疼痛','NRS 疼痛评分量表',95,21],['重度疼痛','NRS 疼痛评分量表',61,13],['爆发痛','NRS 疼痛评分量表',31,2]],
    '老年患者':[['60–69 岁','患者基本信息采集',207,130],['70–79 岁','患者基本信息采集',143,102],['80 岁及以上','患者基本信息采集',48,39]]
  };
  const getDomains=row=>{const name=row.querySelector('td:first-child b')?.textContent.trim();if(domainStats[name])return domainStats[name];const content=row.dataset.domains||row.querySelector('td:first-child small')?.textContent.replace('标签值域：','')||'';return content.split('、').filter(Boolean).map(value=>[value,row.dataset.scale==='all'?'未关联量表':row.dataset.scale,0,0])};
  const closeDomainDetails=()=>document.querySelectorAll('#definitions > tbody > .tag-domain-detail').forEach(detail=>{detail.previousElementSibling?.classList.remove('expanded');detail.remove()});
  document.querySelector('#definitions tbody').addEventListener('click',event=>{const button=event.target.closest('.tag-status-action');if(button){const row=button.closest('tr'),online=row.dataset.status==='online',status=row.querySelector('td:nth-last-child(2) .pill');row.dataset.status=online?'offline':'online';status.textContent=online?'已下架':'使用中';status.className=`pill ${online?'gray':'green'}`;button.textContent=online?'上架':'下架';return}const row=event.target.closest('#definitions > tbody > tr');if(!row||row.classList.contains('tag-domain-detail'))return;const next=row.nextElementSibling;if(next?.classList.contains('tag-domain-detail')){closeDomainDetails();return}closeDomainDetails();const tagName=row.querySelector('td:first-child b')?.textContent.trim()||'该标签',detail=document.createElement('tr');detail.className='tag-domain-detail';detail.innerHTML='<td colspan="5"><div class="tag-domain-wrap"><div class="tag-domain-head"><div><b>'+tagName+' · 值域填写情况</b><small>展示各值域对应的量表填写次数与标签命中数。</small></div><span>收起</span></div><table class="tag-domain-table"><thead><tr><th>标签值域</th><th>关联量表</th><th>量表填写次数</th><th>标签命中数</th></tr></thead><tbody>'+getDomains(row).map(item=>'<tr><td><em class="pill blue">'+item[0]+'</em></td><td>'+item[1]+'</td><td>'+item[2]+'</td><td><b>'+item[3]+'</b></td></tr>').join('')+'</tbody></table></div></td>';row.after(detail);row.classList.add('expanded')});
  const modal=document.querySelector('#tagAddModal'),form=document.querySelector('#tagAddForm'),newProject=document.querySelector('#newTagProject'),newName=document.querySelector('#newTagName'),newRule=document.querySelector('#newTagRule'),domains=document.querySelector('#tagDomainInputs'),formError=document.querySelector('#tagFormError');
  const escapeHtml=value=>value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const addDomain=()=>{const row=document.createElement('div');row.className='tag-domain-input-row';row.innerHTML='<input class="tag-domain-input" maxlength="30" placeholder="请输入标签值域"><button class="domain-remove" type="button" aria-label="删除此值域">×</button>';domains.appendChild(row);row.querySelector('input').focus()};
  const closeModal=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true');form.reset();domains.innerHTML='<div class="tag-domain-input-row"><input class="tag-domain-input" maxlength="30" placeholder="请输入标签值域"><button class="domain-remove" type="button" aria-label="删除此值域" hidden>×</button></div>';formError.hidden=true};
  document.querySelector('#addTag').addEventListener('click',()=>{modal.classList.add('show');modal.setAttribute('aria-hidden','false');newProject.focus()});
  document.querySelector('#closeTagModal').addEventListener('click',closeModal);document.querySelector('#cancelTag').addEventListener('click',closeModal);document.querySelector('#addTagDomain').addEventListener('click',addDomain);
  domains.addEventListener('click',event=>{const button=event.target.closest('.domain-remove');if(button)button.closest('.tag-domain-input-row').remove()});
  domains.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();addDomain()}});
  modal.addEventListener('click',event=>{if(event.target===modal)closeModal()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal.classList.contains('show'))closeModal()});
  form.addEventListener('submit',event=>{event.preventDefault();const projectName=newProject.value,name=newName.value.trim(),rule=newRule.value,values=[...domains.querySelectorAll('.tag-domain-input')].map(item=>item.value.trim()).filter(Boolean);if(!projectName||!name||!values.length){formError.hidden=false;return}const code='TAG_CUSTOM_'+Date.now().toString().slice(-8),row=document.createElement('tr');row.dataset.project=projectName;row.dataset.scale='all';row.dataset.status='online';row.dataset.rule=rule;row.dataset.domains=values.join('、');row.innerHTML='<td><b>'+escapeHtml(name)+'</b><small>标签值域：'+values.map(escapeHtml).join('、')+'</small></td><td>'+escapeHtml(projectName)+'</td><td class="code">'+code+'</td><td><em class="pill green">使用中</em></td><td><button class="text-action tag-status-action" type="button">下架</button></td>';document.querySelector('#definitions tbody').prepend(row);project.value=projectName;refreshScales();filterRows();closeModal()});
});
