document.addEventListener('DOMContentLoaded',()=>{
  const $=selector=>document.querySelector(selector);let editing=null;
  const statuses=[['待提交','00'],['待审核','10'],['驳回','15'],['镁信后台审核通过','20'],['审核通过','20'],['药师驳回','21'],['药店确认，待付款','25'],['付款完成，待药店上传发票','30'],['发票待审核','40'],['发票审核不通过','55'],['发票审核通过','60'],['报案成功，待上传文件','80'],['理赔中','85'],['理赔完成','90'],['理赔失败','91'],['已完成','95'],['理赔销案','92'],['案件退回','93'],['支付信息审核','94']];
  const escapeHtml=value=>String(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const seed=()=>statuses.map(([name,code],index)=>({id:`status-${code}-${index}`,name,code,content:`您的案件状态已更新为「${name}」，请及时查看并按提示处理。`,channels:['企业微信'],miniLink:'',miniTitle:'',miniCardName:'',imageName:'',enabled:index!==2}));
  const load=()=>{try{const saved=JSON.parse(localStorage.getItem('statusMessagePushAllConfigs')||'');return Array.isArray(saved)?saved:seed()}catch{return seed()}};let data=load();data.forEach(item=>item.channels=['企业微信']);const save=()=>localStorage.setItem('statusMessagePushAllConfigs',JSON.stringify(data));
  $('#channelSms')?.closest('label')?.remove();$('#channelApp')?.closest('label')?.remove();$('#channelWecom').checked=true;$('#channelWecom').disabled=true;
  $('#messageForm .form-grid').insertAdjacentHTML('beforeend','<label>小程序链接<input id="miniLink" type="url" placeholder="请输入小程序链接"></label><label>小程序标题<input id="miniTitle" maxlength="40" placeholder="请输入小程序卡片标题"></label><label class="full">小程序卡片<input id="miniCard" type="file" accept="image/*"><small class="asset-note" id="miniCardCurrent">未选择卡片素材</small></label><label class="full">图片素材<input id="imageMaterial" type="file" accept="image/*"><small class="asset-note" id="imageMaterialCurrent">未选择图片素材</small></label>');
  const render=()=>{$('#statusTable tbody').innerHTML=data.map(item=>`<tr><td><b>${escapeHtml(item.name)}</b></td><td class="code">${item.code}</td><td><div class="message-summary"><b>消息：</b><span title="${escapeHtml(item.content)}">${escapeHtml(item.content)}</span></div></td><td>${item.channels.map(channel=>`<span class="pill blue">${channel}</span>`).join(' ')}</td><td><span class="pill ${item.enabled?'green':'gray'}">${item.enabled?'已启用':'已停用'}</span></td><td><button class="text-action configure" data-id="${item.id}">配置</button><button class="text-action toggle" data-id="${item.id}">${item.enabled?'停用':'启用'}</button></td></tr>`).join('')};
  const closeModal=()=>{$('#messageModal').classList.remove('show');$('#messageModal').setAttribute('aria-hidden','true')};
  const openModal=item=>{editing=item;$('#modalSubtitle').textContent=`配置「${item.name}」状态触发后的消息内容。`;$('#modalStatusName').textContent=item.name;$('#modalStatusCode').textContent=item.code;$('#messageContent').value=item.content;$('#channelWecom').checked=true;$('#miniLink').value=item.miniLink||'';$('#miniTitle').value=item.miniTitle||'';$('#miniCard').value='';$('#imageMaterial').value='';$('#miniCardCurrent').textContent=item.miniCardName?`当前卡片：${item.miniCardName}`:'未选择卡片素材';$('#imageMaterialCurrent').textContent=item.imageName?`当前图片：${item.imageName}`:'未选择图片素材';$('#messageModal').classList.add('show');$('#messageModal').setAttribute('aria-hidden','false')};
  $('#statusTable tbody').addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const item=data.find(row=>row.id===button.dataset.id);if(!item)return;if(button.classList.contains('configure'))openModal(item);if(button.classList.contains('toggle')){item.enabled=!item.enabled;save();render()}});
  $('#messageForm').addEventListener('submit',event=>{event.preventDefault();const content=$('#messageContent').value.trim();if(!content){alert('请填写推送内容');return}editing.content=content;editing.channels=['企业微信'];editing.miniLink=$('#miniLink').value.trim();editing.miniTitle=$('#miniTitle').value.trim();editing.miniCardName=$('#miniCard').files[0]?.name||editing.miniCardName||'';editing.imageName=$('#imageMaterial').files[0]?.name||editing.imageName||'';save();closeModal();render()});
  $('#closeMessageModal').addEventListener('click',closeModal);$('#cancelMessage').addEventListener('click',closeModal);$('#messageModal').addEventListener('click',event=>{if(event.target===event.currentTarget)closeModal()});render();
});
